### ISSUE TITLE
Add edge cases to story tasks

### ISSUE THREAD

**Issue by sardred** [IT2901-24-2018/vapi#116]
Should write edge cases for all user stories that have edge cases. Could be used for Use cases in report and potential improvements of the product. Important to document what we have implemented and what we have not (at least that we know should be implemented)

- [x] Tasks belonging to Sprint 2 has defined edge cases
- [x] Tasks belonging to Sprint 3 has defined edge cases
- [ ] Tasks belonging to Sprint 4 has defined edge cases
- [ ] Tasks belonging to Sprint 5 has defined edge cases
- [ ] Possible improvements for system should be written

**Comment by DjCreztian** [comment]
[Link to wiki](https://github.com/IT2901-24-2018/orm/wiki/Edge-cases) with the edge cases described this far. Including possible improvements in wikipage.

**Comment by DjCreztian** [comment]
rendundant with multiple tasks, embrik and håvard has to QA edge cases and eventually provide more cases.
