### ISSUE TITLE
Go through chapter 2

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/vapi#130]
Check updates:
- [x]  in 2.1.2 Agile methods (intro and Scrum) 
- [x] Chapter 2.1.3 Lean, with some changes to Kanban
- [x] Chapter 2.3 Research summary
- [x] Comments in whole chapter

**Comment by Pontius1007** [comment]
Lest og kommentert. Neste person krysser av på sjekklisten etter endt korrigering.

**Comment by Goggman** [comment]
Overall changes seems good. Added some small comments and changes of my own, but none are groundbreaking. Need some followup by Embrik on his comments.
