### ISSUE TITLE
Go through chapter 4.2 making sure that we:

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/vapi#139]
- [x] Don't justify choices again, should be done in section 2.3

**Comment by DjCreztian** [comment]
A lot of suggestions to changes and additions are made. Some comments that needs discussion. Has to be gone through again by 2 people to ensure quality. All subsections of 4.2 containing text.

@Sebba513 and one more should go through ensuring quality.

**Comment by Sebba513** [comment]
Gone through and approved/suggested.
