### ISSUE TITLE
Torgeir report todos:

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/vapi#156]
General:
- [x] Write about risks we have met and how we handled them in 11.2.3

Non-functional requirements for future developers to consider: Chapter 5.4.2
- These should be described as possible future characteristics that someone can add
   - Integrity might be relevant, should relate to some specific means
   - Data is not sensitive yet, but may be in the future
   - [x] Add concerns of future developers about these possibilities
   - [x] Describe NFR that could be relevant for future developers

**Comment by DjCreztian** [comment]
Not sure if the descriptions of NFR and how to solve them are correct, If they are I have misunderstood them

**Comment by sardred** [comment]
Will run QA now:

- [ ] 11.2.3
- [ ] 5.4.2 (will keep in mind specifically mentions of open source)

**Comment by sardred** [comment]
Made suggestions to 11.2.3, added some suggestions, but mostly comments requesting change to 5.4.2. A lot of the text feels very theoretical, when we now after the project should *know* which requirements are met, and to what degree. General wording like "could" and "might be" implies that we don't know, or haven't bothered looking into what is needed from future developers.
I feel like 5.4.2 should maybe also include notes on what would potentially be required if the API was to be used by a map-based application in the future. For example, would story 26 be needed for the frontend not to take a million years to load?
Moving back to todo

**Comment by DjCreztian** [comment]
Seems could, should be gone through again with techies when product is final
