### ISSUE TITLE
Write Chapter 9: Sprints

### ISSUE THREAD

**Issue by Sebba513** [IT2901-24-2018/vapi#171]

**Comment by DjCreztian** [comment]
Seems good, but I wonder if it is enough? Nektaria said we should show the work done in Sprints and the outcome. Is the sub sections desctriptive enough?

**Comment by sardred** [comment]
Stuff I'll do:

- [ ] Go through and give the @sardred Stamp of Sort-of Approval :tm: 
- [ ] Add summarized retrospective notes to each sprint

We also need to:

- [ ] Added resource graph for sprint 5

**Comment by sardred** [comment]
I've gone through and written in suggestions for chapter 9 now, excluding the section for sprint 5 which I'll deal with when the sprint is over. Noted it in a comment.

**Comment by sardred** [comment]
Closing because my suggestions were approved
