### ISSUE TITLE
QA Report sections:

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/vapi#172]
Chapter 1.6 Limitations of this study:
- [x] Enough text?
- [x] Correct interpretation of the requested chapters?

Chapter 10.3 and 10.4:
- [ ] Should explain more about the limitations of our study (system), somewhat relating to the introduction chapter 1.6.

Chapter 4.6.2:
- [x] What is Project Movement and how does it relate to VAPI

Chapter 11.2.1:
- [x] Problems with our customer and what we did to handle them

Chapter 7:
- [ ] All diagrams should have e description that explains them

**Comment by sardred** [comment]
I cleared 1.6, 4.6.2 and 11.2.1. 
Remains to be QA'd by someone:

- [ ] 10.3 and 10.4, explain limitations of our study more in-depth related to the system
- [ ] Chapter 7 diagrams should have descriptions
