### ISSUE TITLE
Make a wiki page for future developers

### ISSUE THREAD

**Issue by sardred** [IT2901-24-2018/vapi#179]
Our wiki is sort of a mess, but even when it gets cleaned up, there is a lot of information that is only relevant to our project as opposed to the product.
We should make a "for future developers" page that details some of the information we have for them, and add a link to it in our `README.md` so it's easy to find.
Doesn't have to be long, but here are a few things to note:
- [ ] What endpoints have what permissions. How do we imagine a prod-system would use users? Are everybody superusers? Or just the people that put Vapi on their server? What is the intended usage?
- [x] What non-functional requirements do they need to keep in mind before releasing Vapi onto a server? See 5.4.2 in our report.
- [x] What are the edge cases they need to consider handling?
- [ ] What is the status of our functionality? For example, is our segmenting rough and in need of optimization? Is the mapping a bit dumb, and should be looked at?

**Comment by DjCreztian** [comment]
edge cases are, if not final, at least started on

**Comment by DjCreztian** [comment]
https://github.com/IT2901-24-2018/vapi/wiki/Functional-and-non-functional-requirements

**Comment by plusk** [comment]
We decided we didn't want to do this with the time we had left.
