### ISSUE TITLE
Wiki pages lacking content

### ISSUE THREAD

**Issue by DjCreztian** [IT2901-24-2018/vapi#184]
Pages without content that must be written or removed
- [x] [Getting started](https://github.com/IT2901-24-2018/bit24/wiki/Getting-started)
- [x] [How to use](https://github.com/IT2901-24-2018/bit24/wiki/How-to-use)
- [x] FAQ sub-page, [Operational](https://github.com/IT2901-24-2018/bit24/wiki/FAQ:-Operational)
    - Dropping this

Pages that needs update with new information
- [x] New [Homepage](https://github.com/IT2901-24-2018/vapi/wiki) with links to everything
- [x] [Possible improvements](https://github.com/IT2901-24-2018/orm/wiki/Edge-cases)
   - new edge cases for tasks
   - I assume API docs and Docker container does not have edge cases
- [x] [Customer clarifications](https://github.com/IT2901-24-2018/bit24/wiki/Customer-clarifications)
   - do we have any? Nope - Mr. T
- [x] [General](https://github.com/IT2901-24-2018/bit24/wiki/FAQ:-General)
   - really thin
   - add links to mapmatching when they are done
- [x] [Functional and non-functional requirements](https://github.com/IT2901-24-2018/bit24/wiki/Functional-and-non-functional-requirements)
   - Go through NFR so they are updated from the report
- [x] MET API
    - Redundant when we have Weather Data 
- [x] REST API
    - Need updates

All pages must be gone through QA
- [x] QA whoop

**Comment by Goggman** [comment]
Should we merge input production data with How to use?
